spring:
  application:
    name: spring-cloud-eureka-feign-client
  thymeleaf:
    mode: HTML
    cache: false

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}